//! `oxikube_assets` — layer: `platform`.
//!
//! Embedded assets: Lucide icons, fonts, bundled themes, default settings/keymaps.
//!
//! Module map:
//! - [`icons`]: [`IconName`], the closed enum of Lucide SVGs Oxikube ships. Only the icons listed
//!   there are embedded in the binary, so an unused icon costs nothing.
//! - [`source`]: [`Assets`], the `gpui::AssetSource` that serves those icons by path
//!   (`icons/<name>.svg`).
//! - [`settings`]: the settings assets (E05-S06), embedded with `include_str!`:
//!   [`default_settings`] (`assets/settings/default.json`, the bottom layer of the settings
//!   store), [`initial_user_settings_content`] (the commented template written to a new user
//!   `settings.json` on first run) and [`settings_schema`] (`settings.schema.json`, generated by
//!   `cargo xtask gen-settings-schema` and checked in CI).
//!
//! - [`keymap`]: the keymap assets (E05-S07): [`default_keymap`] per OS ([`KeymapPlatform`]),
//!   the optional [`vim_keymap`] layer and [`initial_user_keymap_content`].
//!
//! Fonts and bundled themes join this crate with their own story (E05-S08). `oxikube_ui` composes [`Assets`] with the component library's own icon
//! bundle; applications register the composite when they build the GPUI `Application`.
//!
//! See `README.md` in this crate and `docs/ARCHITECTURE.md` for the allowed
//! dependency direction. `cargo xtask lint-deps` enforces it.

pub mod icons;
pub mod keymap;
pub mod settings;
pub mod source;

pub use icons::IconName;
pub use keymap::{KeymapPlatform, default_keymap, initial_user_keymap_content, vim_keymap};
pub use settings::{
    SETTINGS_SCHEMA_PATH, default_settings, initial_user_settings_content, settings_schema,
};
pub use source::Assets;
