//! The key dictionary: the object keys Kubernetes objects repeat, stored as a small number in a
//! [`JsonDoc`](super::JsonDoc) instead of their text.
//!
//! A pod has about 150 keys and nearly all of them come from this list (`metadata`, `containers`,
//! `lastTransitionTime`, ...), so a key costs one byte instead of a heap `String` and its text. A key
//! not in the list (a label, an annotation, a CRD field) is stored inline, byte for byte.
//!
//! The list is part of the encoding but not of any stored data: documents are never persisted, so
//! it can grow or be reordered freely. Ids are positions in [`KEYS`]; the most frequent keys come
//! first so they fit the one-byte form of a varint (ids below 127).

use std::sync::OnceLock;

/// Every dictionary key, most frequent first. Position + 1 is the key's code (0 means "inline").
pub(super) const KEYS: &[&str] = &[
    "name",
    "status",
    "type",
    "lastTransitionTime",
    "kind",
    "apiVersion",
    "uid",
    "metadata",
    "reason",
    "spec",
    "memory",
    "image",
    "resourceVersion",
    "creationTimestamp",
    "labels",
    "namespace",
    "app",
    "key",
    "effect",
    "cpu",
    "path",
    "operator",
    "tolerationSeconds",
    "conditions",
    "ip",
    "containers",
    "resources",
    "requests",
    "lastHeartbeatTime",
    "phase",
    "restartPolicy",
    "port",
    "startTime",
    "pod-template-hash",
    "ready",
    "started",
    "restartCount",
    "state",
    "ports",
    "protocol",
    "ownerReferences",
    "controller",
    "blockOwnerDeletion",
    "serviceAccountName",
    "qosClass",
    "message",
    "imagePullPolicy",
    "containerPort",
    "limits",
    "readinessProbe",
    "livenessProbe",
    "startupProbe",
    "httpGet",
    "scheme",
    "periodSeconds",
    "initialDelaySeconds",
    "timeoutSeconds",
    "successThreshold",
    "failureThreshold",
    "volumeMounts",
    "mountPath",
    "readOnly",
    "terminationMessagePath",
    "terminationMessagePolicy",
    "dnsPolicy",
    "schedulerName",
    "terminationGracePeriodSeconds",
    "tolerations",
    "volumes",
    "projected",
    "sources",
    "serviceAccountToken",
    "expirationSeconds",
    "nodeName",
    "hostIP",
    "hostIPs",
    "imageID",
    "lastState",
    "containerStatuses",
    "startedAt",
    "replicas",
    "address",
    "pods",
    "ephemeral-storage",
    "podIP",
    "podIPs",
    "annotations",
    "template",
    "containerID",
    "running",
    "selector",
    "capacity",
    "terminated",
    "exitCode",
    "finishedAt",
    "waiting",
    "matchLabels",
    "generation",
    "observedGeneration",
    "data",
    "env",
    "envFrom",
    "valueFrom",
    "value",
    "args",
    "command",
    "workingDir",
    "securityContext",
    "configMap",
    "secret",
    "emptyDir",
    "hostPath",
    "persistentVolumeClaim",
    "claimName",
    "defaultMode",
    "items",
    "downwardAPI",
    "fieldRef",
    "fieldPath",
    "configMapKeyRef",
    "secretKeyRef",
    "optional",
    "subPath",
    "generateName",
    "finalizers",
    "deletionTimestamp",
    "deletionGracePeriodSeconds",
    "managedFields",
    "affinity",
    "nodeAffinity",
    "podAffinity",
    "podAntiAffinity",
    "topologySpreadConstraints",
    "priority",
    "priorityClassName",
    "preemptionPolicy",
    "enableServiceLinks",
    "hostNetwork",
    "hostPID",
    "hostname",
    "subdomain",
    "serviceAccount",
    "automountServiceAccountToken",
    "imagePullSecrets",
    "nominatedNodeName",
    "initContainers",
    "initContainerStatuses",
    "ephemeralContainers",
    "ephemeralContainerStatuses",
    "lastProbeTime",
    "allocatedResources",
    "runAsUser",
    "runAsGroup",
    "runAsNonRoot",
    "fsGroup",
    "capabilities",
    "drop",
    "add",
    "privileged",
    "allowPrivilegeEscalation",
    "readOnlyRootFilesystem",
    "seccompProfile",
    "exec",
    "tcpSocket",
    "lifecycle",
    "preStop",
    "postStart",
    "addresses",
    "allocatable",
    "daemonEndpoints",
    "kubeletEndpoint",
    "Port",
    "nodeInfo",
    "architecture",
    "bootID",
    "containerRuntimeVersion",
    "kernelVersion",
    "kubeProxyVersion",
    "kubeletVersion",
    "machineID",
    "operatingSystem",
    "osImage",
    "systemUUID",
    "podCIDR",
    "podCIDRs",
    "providerID",
    "taints",
    "timeAdded",
    "unschedulable",
    "images",
    "names",
    "sizeBytes",
    "volumesInUse",
    "volumesAttached",
    "strategy",
    "updateStrategy",
    "rollingUpdate",
    "maxSurge",
    "maxUnavailable",
    "partition",
    "revisionHistoryLimit",
    "progressDeadlineSeconds",
    "minReadySeconds",
    "readyReplicas",
    "availableReplicas",
    "updatedReplicas",
    "currentReplicas",
    "unavailableReplicas",
    "fullyLabeledReplicas",
    "collisionCount",
    "currentRevision",
    "updateRevision",
    "serviceName",
    "podManagementPolicy",
    "volumeClaimTemplates",
    "desiredNumberScheduled",
    "currentNumberScheduled",
    "numberMisscheduled",
    "updatedNumberScheduled",
    "numberReady",
    "numberAvailable",
    "numberUnavailable",
    "completions",
    "parallelism",
    "backoffLimit",
    "completionTime",
    "succeeded",
    "failed",
    "active",
    "ttlSecondsAfterFinished",
    "schedule",
    "timeZone",
    "suspend",
    "concurrencyPolicy",
    "successfulJobsHistoryLimit",
    "failedJobsHistoryLimit",
    "jobTemplate",
    "lastScheduleTime",
    "lastSuccessfulTime",
    "clusterIP",
    "clusterIPs",
    "externalIPs",
    "externalName",
    "targetPort",
    "nodePort",
    "appProtocol",
    "sessionAffinity",
    "ipFamilies",
    "ipFamilyPolicy",
    "internalTrafficPolicy",
    "loadBalancer",
    "ingress",
    "endpoints",
    "subsets",
    "notReadyAddresses",
    "targetRef",
    "serving",
    "terminating",
    "ingressClassName",
    "rules",
    "host",
    "http",
    "paths",
    "pathType",
    "backend",
    "service",
    "number",
    "tls",
    "hosts",
    "secretName",
    "storage",
    "accessModes",
    "storageClassName",
    "volumeMode",
    "volumeName",
    "binaryData",
    "immutable",
    "stringData",
    "verbs",
    "apiGroups",
    "resourceNames",
    "roleRef",
    "subjects",
    "aggregationRule",
    "apiGroup",
    "involvedObject",
    "source",
    "component",
    "firstTimestamp",
    "lastTimestamp",
    "count",
    "eventTime",
    "action",
    "note",
    "regarding",
    "related",
    "reportingController",
    "reportingComponent",
    "reportingInstance",
    "series",
    "lastObservedTime",
    "scaleTargetRef",
    "minReplicas",
    "maxReplicas",
    "metrics",
    "desiredReplicas",
    "currentMetrics",
    "current",
    "target",
    "averageUtilization",
    "averageValue",
    "group",
    "scope",
    "plural",
    "singular",
    "listKind",
    "shortNames",
    "categories",
    "versions",
    "served",
    "schema",
    "openAPIV3Schema",
    "properties",
    "enum",
    "minimum",
    "subresources",
    "additionalPrinterColumns",
    "jsonPath",
    "acceptedNames",
    "storedVersions",
    "description",
    "format",
    "required",
    "release",
    "version",
    "tier",
    "owner",
    "size",
    "resource",
    "modifiedAt",
    "username",
    "password",
    "app.kubernetes.io/name",
    "app.kubernetes.io/instance",
    "app.kubernetes.io/version",
    "app.kubernetes.io/component",
    "app.kubernetes.io/part-of",
    "app.kubernetes.io/managed-by",
    "kubernetes.io/hostname",
    "kubernetes.io/os",
    "kubernetes.io/arch",
    "kubernetes.io/metadata.name",
    "node-role.kubernetes.io/control-plane",
    "node.kubernetes.io/instance-type",
    "topology.kubernetes.io/zone",
    "topology.kubernetes.io/region",
    "beta.kubernetes.io/os",
    "beta.kubernetes.io/arch",
    "controller-revision-hash",
    "statefulset.kubernetes.io/pod-name",
    "batch.kubernetes.io/job-name",
    "batch.kubernetes.io/controller-uid",
    "job-name",
    "controller-uid",
    "k8s-app",
    "helm.sh/chart",
    "deployment.kubernetes.io/revision",
    "deployment.kubernetes.io/desired-replicas",
    "deployment.kubernetes.io/max-replicas",
    "kubectl.kubernetes.io/restartedAt",
    "kubectl.kubernetes.io/last-applied-configuration",
    "kubernetes.io/config.seen",
    "kubernetes.io/config.source",
    "kubernetes.io/psp",
    "node.alpha.kubernetes.io/ttl",
    "volumes.kubernetes.io/controller-managed-attach-detach",
    "cni.projectcalico.org/podIP",
    "cni.projectcalico.org/podIPs",
];

/// The inline marker: the key text follows.
pub(super) const INLINE: u64 = 0;

/// `(key, code)` pairs sorted by key, built on first use.
fn index() -> &'static [(&'static str, u16)] {
    static INDEX: OnceLock<Vec<(&'static str, u16)>> = OnceLock::new();
    INDEX.get_or_init(|| {
        let mut index: Vec<(&'static str, u16)> = KEYS
            .iter()
            .enumerate()
            .map(|(i, key)| (*key, u16::try_from(i + 1).unwrap_or(u16::MAX)))
            .collect();
        // A key listed twice keeps its first (more frequent) position.
        index.sort_by(|a, b| a.0.cmp(b.0).then(a.1.cmp(&b.1)));
        index.dedup_by(|later, earlier| later.0 == earlier.0);
        index
    })
}

/// The code of `key` (`1..`), or `None` when it is not in the dictionary.
pub(super) fn code_of(key: &str) -> Option<u64> {
    let index = index();
    index
        .binary_search_by(|(k, _)| (*k).cmp(key))
        .ok()
        .map(|at| u64::from(index[at].1))
}

/// The key a code (`1..`) stands for.
pub(super) fn key_of(code: u64) -> Option<&'static str> {
    let at = usize::try_from(code.checked_sub(1)?).ok()?;
    KEYS.get(at).copied()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_key_round_trips_through_its_code() {
        for key in KEYS {
            let code = code_of(key).expect("listed keys have a code");
            assert_eq!(key_of(code), Some(*key));
        }
    }

    #[test]
    fn unknown_keys_have_no_code() {
        assert_eq!(code_of("not-a-kubernetes-key"), None);
        assert_eq!(key_of(0), None);
        assert_eq!(key_of(KEYS.len() as u64 + 1), None);
    }

    #[test]
    fn the_hot_keys_fit_one_varint_byte() {
        for key in ["name", "metadata", "spec", "status", "labels", "containers"] {
            assert!(code_of(key).unwrap() < 128, "{key}");
        }
    }
}
