//! JSON schema for `settings.json`, generated from the registered settings with `schemars`.
//!
//! Follows Zed's generator: draft 2019-09, unknown fields denied (so editors flag typos),
//! `allowTrailingCommas` for the VS Code JSON language service. Each setting contributes its
//! content schema at its key (root-level content contributes its fields); `clusters` maps a
//! cluster id to an object accepting the same settings. Object keys are sorted recursively,
//! so the output depends only on the registered types, never on registration order.
//!
//! `cargo xtask gen-settings-schema` writes the result to
//! [`oxikube_assets::SETTINGS_SCHEMA_PATH`]; `--check` fails CI when it is stale.

use schemars::{JsonSchema, SchemaGenerator, generate::SchemaSettings};
use serde_json::{Map, Value, json};

use crate::diagnostics::{CLUSTERS_KEY, SCHEMA_KEY};

/// Name of the shared definition for one cluster's overrides.
const CLUSTER_DEF: &str = "ClusterSettings";

/// The generator every section schema is produced with.
pub(crate) fn generator() -> SchemaGenerator {
    SchemaSettings::draft2019_09().into_generator()
}

/// `T`'s schema with every subschema inlined (no `$ref`s except for recursive types), for
/// walking its keys.
pub(crate) fn inline_schema_for<T: JsonSchema>() -> Value {
    SchemaSettings::draft2019_09()
        .with(|settings| settings.inline_subschemas = true)
        .into_generator()
        .into_root_schema_for::<T>()
        .to_value()
}

/// `subschema_for::<T>()` as a plain value.
pub(crate) fn section_schema<T: JsonSchema>(generator: &mut SchemaGenerator) -> Value {
    generator.subschema_for::<T>().to_value()
}

/// Build the document from `(key, type name, schema)` sections, sorted by the caller.
pub(crate) fn assemble(
    sections: Vec<(Option<&'static str>, &'static str, Value)>,
    mut generator: SchemaGenerator,
) -> Value {
    let mut definitions = generator.take_definitions(true);
    let mut properties = Map::new();
    for (key, _type_name, schema) in sections {
        match key {
            Some(key) => {
                properties.insert(key.to_owned(), schema);
            }
            None => {
                let fields = resolve_ref(&schema, &definitions)
                    .and_then(|schema| schema.get("properties"))
                    .and_then(Value::as_object)
                    .cloned()
                    .unwrap_or_default();
                properties.extend(fields);
            }
        }
    }

    definitions.insert(
        CLUSTER_DEF.to_owned(),
        json!({
            "description": "Overrides for one cluster: the per-cluster settings (display name, colour, read-only, default namespace, terminal directory, node shell, Prometheus, accessible namespaces, exec policy) and any other setting. Layers merge field by field: defaults, then the top-level values, then this block.",
            "type": "object",
            "properties": properties.clone(),
        }),
    );
    properties.insert(
        CLUSTERS_KEY.to_owned(),
        json!({
            "description": "Per-cluster overrides, keyed by cluster id (16 hex characters). Changes to read_only, colour and display_name apply to open sessions at once; exec_interactivity applies on the next connect; default_namespace applies to new sessions.",
            "type": "object",
            "examples": [{
                "3f2a9c1b7d4e8a60": {
                    "display_name": "Production (eu-west)",
                    "colour": "#e5484d",
                    "read_only": true,
                    "default_namespace": "payments",
                    "prometheus": {
                        "url": "https://prometheus.example.com",
                        "auth_secret": "prod-prometheus"
                    }
                }
            }],
            "additionalProperties": { "$ref": format!("#/$defs/{CLUSTER_DEF}") },
        }),
    );
    properties.insert(
        SCHEMA_KEY.to_owned(),
        json!({ "description": "Schema reference for editors.", "type": "string" }),
    );

    let mut document = json!({
        "$schema": "https://json-schema.org/draft/2019-09/schema",
        "title": "Oxikube settings",
        "description": "User settings.json for Oxikube. Generated by `cargo xtask gen-settings-schema`; do not edit.",
        "type": "object",
        "allowTrailingCommas": true,
        "properties": properties,
        "$defs": definitions,
    });
    deny_unknown_fields(&mut document);
    sort_keys(&mut document)
}

/// Follow a local `#/$defs/<name>` reference.
fn resolve_ref<'a>(schema: &'a Value, definitions: &'a Map<String, Value>) -> Option<&'a Value> {
    match schema.get("$ref").and_then(Value::as_str) {
        Some(reference) => definitions.get(reference.strip_prefix("#/$defs/")?),
        None => Some(schema),
    }
}

/// Zed's `DefaultDenyUnknownFields`: every object schema with fixed `properties` and no
/// `additionalProperties` rejects other keys.
fn deny_unknown_fields(value: &mut Value) {
    match value {
        Value::Object(map) => {
            if map.get("properties").is_some_and(Value::is_object)
                && !map.contains_key("additionalProperties")
            {
                map.insert("additionalProperties".to_owned(), Value::Bool(false));
            }
            map.values_mut().for_each(deny_unknown_fields);
        }
        Value::Array(items) => items.iter_mut().for_each(deny_unknown_fields),
        _ => {}
    }
}

/// `value` with object keys sorted at every depth.
fn sort_keys(value: &mut Value) -> Value {
    match value {
        Value::Object(map) => {
            let mut entries: Vec<_> = std::mem::take(map).into_iter().collect();
            entries.sort_by(|a, b| a.0.cmp(&b.0));
            Value::Object(
                entries
                    .into_iter()
                    .map(|(key, mut sub)| (key, sort_keys(&mut sub)))
                    .collect(),
            )
        }
        Value::Array(items) => Value::Array(items.iter_mut().map(sort_keys).collect()),
        other => other.take(),
    }
}

/// Serialise a schema the way the checked-in file is written: two-space indent, trailing
/// newline.
pub fn to_schema_text(schema: &Value) -> String {
    let mut text = serde_json::to_string_pretty(schema).unwrap_or_default();
    text.push('\n');
    text
}
